FROM golang:1.11-alpine AS build
RUN apk add --update --no-cache gcc git build-base


WORKDIR /go/src/app
ADD ./src /go/src/app

RUN CGO_ENABLED=0 go build -o /bin/main

FROM scratch
COPY --from=build /bin/main /bin/main

#EXPOSE 8000

WORKDIR /go/src/app
ENTRYPOINT ["/bin/main"]
